let StockProductos = [
    {id: 1, nombre:"aaa", tipo:"Remeras", precio: 3000 },
    {id: 2, nombre: "aaa", tipo:"Remeras", precio: 3000},
    {id: 3, nombre: "aaa", tipo:"Remeras", precio: 3500},
    {id: 4, nombre: "aaa", tipo:"Remeras", precio: 3000},
    {id: 5, nombre: "aaa", tipo:"Remeras", precio: 3500},
    {id: 6, nombre: "aaa", tipo:"Remeras", precio: 3500},
    {id: 7, nombre: "aaa", tipo:"Remeras", precio: 3000},
    {id: 8, nombre: "aaa", tipo:"Remeras", precio: 3000},
    {id: 9, nombre: "aaa", tipo:"Remeras", precio: 3000},
    {id: 10, nombre: "aaa", tipo:"Remeras", precio: 3000},
    {id: 11, nombre: "aaa", tipo:"Buzos ", precio: 6000},
    {id: 12, nombre: "aaa", tipo:"Buzos", precio: 6500},
    {id: 13, nombre: "aaa", tipo:"Buzos", precio: 5500},
    {id: 14, nombre: "aaa", tipo:"Buzos", precio: 6000},
    {id: 15, nombre: "aaa", tipo:"Conjuntos", precio: 9000},
    {id: 16, nombre: "aaa", tipo:"Conjuntos", precio: 8500},
    {id: 17, nombre: "aaa", tipo:"Conjuntos", precio: 9000},
    {id: 18, nombre: "aaa", tipo:"Jean", precio: 6000},
    {id: 19, nombre: "aaa", tipo:"Jean", precio: 4000},
    {id: 20, nombre: "aaa", tipo:"Jean", precio: 4000},
    ]; 